#pragma config(Sensor, dgtl1,  driveLeft,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveRight,     sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  button,         sensorTouch)
#pragma config(Motor,  port4,           driveLeftFront, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port5,           driveRightFront, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port6,           driveLeftRear, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port7,           driveRightRear, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TICKS 1000
#define SPEED

task main () {
	//Drives the number of ticks set above

}
