#pragma config(Sensor, dgtl1,  driveLeft,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveRight,     sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  button,         sensorTouch)
#pragma config(Motor,  port4,           driveLeftFront, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port5,           driveRightFront, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port6,           driveLeftRear, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port7,           driveRightRear, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TICKS 1000
#define SPEED 127
#define MOTOR_DEADBAND 10

void setDriveSpeeds (int lf, int rf, int lr, int rr, unsigned int time = 0) {
	if (abs(lf) > MOTOR_DEADBAND) motor[driveLeftFront] = lf;
	else motor[driveLeftFront] = 0;
	if (abs(rf) > MOTOR_DEADBAND) motor[driveRightFront] = rf;
	else motor[driveRightFront] = 0;
	if (abs(lr) > MOTOR_DEADBAND) motor[driveLeftRear] = lr;
	else motor[driveLeftRear] = 0;
	if (abs(rr) > MOTOR_DEADBAND) motor[driveRightRear] = rr;
	else motor[driveRightRear] = 0;

	if (time > 0) {
		wait1Msec (time);

		motor[driveLeftFront] = 0;
		motor[driveLeftRear] = 0;
		motor[driveRightFront] = 0;
		motor[driveRightRear] = 0;
	}
}

void driveDistanceTick (int leftTick, int rightTick, int tol = 50, float speed = 1) {
	nMotorEncoder[driveLeftRear] = 0;
	nMotorEncoder[driveRightRear] = 0;

	bool leftOnTarget;
	bool rightOnTarget;

	while (!leftOnTarget && !rightOnTarget) {
		//Initialize motor encoder
		int leftDist = nMotorEncoder[driveLeftFront];
		int rightDist = nMotorEncoder[driveRightFront];

		//Variables to expedite setting the motor speeds
		int leftSpeed;
		int rightSpeed;

		while (!leftOnTarget && !rightOnTarget) {
			//'Alias' variables
			leftSpeed = nMotorEncoder[driveLeftFront];
			rightSpeed = nMotorEncoder[driveRightFront];

			//Check left side
			if (leftDist - tol > leftTick) {
				leftSpeed = -127;
				leftOnTarget = false;
			}
			else if (leftDist + tol < leftTick) {
				leftSpeed = 127;
				leftOnTarget = false;
			}
			else {
				leftSpeed = 0;
				leftOnTarget = true;
			}

			//Check right side
			if (rightDist - tol > rightTick) {
				rightSpeed = -127;
				rightOnTarget = false;
			}
			else if (rightDist + tol < rightTick) {
				rightSpeed = 127;
				rightOnTarget = false;
			}
			else {
				rightSpeed = 0;
				rightOnTarget = true;
			}

			//Set the drive speeds
			setDriveSpeeds (leftSpeed, rightSpeed, leftSpeed, rightSpeed);

			//Loop breaks when they both reach the target
		}
	}
}

task main () {
	//Drives the number of ticks set above
	while (true) {
		driveDistanceTick (TICKS, TICKS, 50, SPEED / 127);
		writeDebugStreamLine("Drove %d ticks", TICKS);

		while (!SensorValue[button]) {}
	}
}
