#pragma config(Sensor, in1,    elevLeft,       sensorPotentiometer)
#pragma config(Sensor, in2,    elevRight,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveLeftEnc,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveRightEnc,  sensorQuadEncoder)
#pragma config(Motor,  port1,           flyLeft,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           elevLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           elevRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveLeftFront, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port5,           driveRightFront, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port6,           driveLeftRear, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port7,           driveRightRear, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port8,           convLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           convRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flyRight,      tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

//Definitions
#define MOTOR_DEADBAND 10

//Includes
#include "Vex_Competition_Includes.c"
#include <MainDriveFunctions.h>


void pre_auton () {

}

task autonomous () {

}

task usercontrol () {
	while (true) {
		driveTank();
	}

	wait1Msec(50);
}
